### ISSUE TITLE
Docs: nested tables overlapping in Firefox

### ISSUE THREAD

**Issue by bnjmnt4n** [taneliang/neh#383]
For some reason, the nested tables overlap with the next cell (tested in Firefox 84 and 86). Works fine on Chromium.

![image](https://user-images.githubusercontent.com/813865/107145769-c95c5780-697e-11eb-9ced-810a86c97a8a.png)

Removing the `.h-full` class from the nested table fixes it for me.

**Comment by taneliang** [comment]
Thanks, feel free to make a PR! If I remember correctly it doesn't parse Firefox search queries properly either, so Firefox is clearly not very well supported unfortunately.

By the way, are you using neh yourself? I was just about to remove all NUS-related things as I've graduated, but I'll be happy to leave them there if you're using it

**Comment by bnjmnt4n** [comment]
Sure I'll send a PR for that. You're right that it doesn't seem to work well with Firefox search queries, seems like it sends `http://{domain}/search+query` instead of `http://{domain}/search%20query`. I'll see if there's anything I can do to fix it. For now, I just added a keyword shortcut for search so I just need to prefix my queries with `n` to get the desired URL.

I'm using neh, so would appreciate if the NUS shortcuts are kept :smile: but no worries if you feel like removing them.

**Comment by taneliang** [comment]
Very cool! I didn't know there were others using this :D Anyway since you're the only one (that I know of) who's using the `nus` handler, feel free to do whatever you want with it. If you PR, just cc me in the PR so that I see it and I can land it quickly :)

Btw, lmk if you want to work on NUSMods too!

**Comment by bnjmnt4n** [comment]
Cool, I'll send PRs here if there's anything I might need (see #387/#388).

> Btw, lmk if you want to work on NUSMods too!

Yeah, I was planning to do an Orbital related to NUSMods (see https://github.com/nusmodifications/nusmods/issues/359#issuecomment-770387587), but I'll definitely send PRs there if I see issues or have suggestions.
